### ISSUE TITLE
Publication of plugins on the Gradle plugin portal.

### ISSUE THREAD

**Issue by ljacomet** [ProtonMail/protoncore_android#5]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
Please reach out to plugin-portal-support@gradle.com regarding your latest plugin submissions, an email was sent to contact@protonmail.com but has been unanswered:

Hello,

The newly published version of your plugin "me.proton.detekt" and others removed the leading "gradle.plugin" from its JAR coordinates.
This is a change we want to promote but know that it might impact users that rely on legacy plugin application.
If this change is desired, please confirm it with us. Without news from your side, we will reject the new submission in 7 days.

Note that all submissions with group prefix "proton.me" have been rejected.

**Comment by neilmarietta** [comment]
Hi,

Sorry for the very late answer.

Proton Core Android don't publish plugin to Gradle Plugin Portal anymore.
